apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name:  build

on:
  workflow_dispatch:
  push:
    branches:
    - '**'

permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write

jobs:
  build:
    if: ${{ vars.workflow_execution_env == 'production' }}
    steps:
    - name: Get source code
      uses: cloudbees-io/checkout@v1
    - name: Setup git credentials
      uses: cloudbees-io/configure-git-global-credentials@v1
      with:
        repositories: calculi-corp/dsl-engine-cli, cloudbees-io/workflow-advisor
    - name: Build, test, scan and push to ECR
      id: buildimage
      uses: calculi-corp/cb-internal-shared-actions/build/action@v8
      with:
        go-binary-build: "true"
        go-build-ldflags: "-X main.version=$(cloudbees.version)"
        go-binary-name: advisor
        kaniko-build: "true"
        run-unit-test: "true"
        registry-url: 020229604682.dkr.ecr.us-east-1.amazonaws.com
        registry-image-name: actions/workflow-advisor
        registry-type: ECR
        oidc-iam-role: ${{ vars.oidc_staging_iam_role }}
    - name: Run TruffleHog Container Action
      uses: cloudbees-io/trufflehog-secret-scan-container@v1
      with:
        image-location: 020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/workflow-advisor
        image-tag: ${{ cloudbees.version }}
